<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Database\Seeders\TodoSeeder;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;
use Illuminate\Support\Facades\DB;


class TodolistControllerTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        DB::delete("delete from todos");
    }

    public function testTodolist()
    {
        $this->seed(TodoSeeder::class);

        $this->withSession([
            "user" => "budi"
            
        ])->get('/todolist')
            ->assertSeeText("1")
            ->assertSeeText("Marcell")
            ->assertSeeText("2")
            ->assertSeeText("Budi");
    }

    public function testAddTodoFailed()
    {
        $this->withSession([
            "user" => "budi"
        ])->post("/todolist", [])
            ->assertSeeText("Todo is required");
    }

    public function testAddTodoSuccess()
    {
        $this->withSession([
            "user" => "budi"
        ])->post("/todolist", [
            "todo" => "Marcell"
        ])->assertRedirect("/todolist");
    }

    public function testRemoveTodolist()
    {
        $this->withSession([
            "user" => "budi",
            "todolist" => [
                [
                    "id" => "1",
                    "todo" => "Marcell"
                ],
                [
                    "id" => "2",
                    "todo" => "Putra"
                ]
            ]
        ])->post("/todolist/1/delete")
            ->assertRedirect("/todolist");
    }
}
